services:
        rabbit-mq:
                image: rabbitmq:3-management
                ports:
                        - 5672:5672
                        - 15672-15672
        mongodb:
                image: mongo:latest
                ports:
                        - 27017-27019:27017-27019
